name: Github Secrets

on:
    workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: |
            echo "MY SECRET: ${{ secrets.MY_SECRET_VAULT }}"
            echo "not_my_secrets: ${{ secrets.no_my_secrets }}"
      - name: Print secret as an environment variable
        run: |
            echo "MY SECRET: $GCP_CREDS"
        env: 
            GCP_CREDS: ${{ secrets.MY_SECRET_VAULT }}
