# This is a basic workflow to help you get started with Actions

name: Custom Env Variables

# Controls when the workflow will run
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday
  sample_var: sample
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mainjob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      Greeting: Dear
      sample_var: sample-1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: print values of env vars
        run: |
          echo "$Greeting $FIRST_NAME. Today is $DAY_OF_WEEK!"
          echo "Sample Vars: $sample_var"
          echo "Sample Vars: ${{ env.sample_var}}"
        env:
          FIRST_NAME: Students
          sample_var: sample-2
